### ISSUE TITLE
Bug in tensor.split

### ISSUE THREAD

**Issue by mukahraman** [haydnv/tinychain#63]
- `tensor.split` only works for `shape[axis] == num_or_size_splits[axis]`

```
import os
import tinychain as tc
import numpy as np

HOST = tc.host.Host(os.getenv("TC_HOST", "http://demo.tinychain.net"))
ENDPOINT = "/transact/hypothetical"

# Working example
cxt = tc.Context()
x = np.ones((6, 30), dtype=np.int64)
cxt.x1 = tc.tensor.Dense.load(x.shape, tc.I64, x.flatten().tolist())
cxt.x2 = cxt.x1.split(6, axis=0)       
actual = HOST.post(ENDPOINT, cxt)

# Should work but throwing Bad request
cxt = tc.Context()
x = np.ones((6, 30), dtype=np.int64)
cxt.x1 = tc.tensor.Dense.load(x.shape, tc.I64, x.flatten().tolist())
cxt.x2 = cxt.x1.split(2, axis=0)
actual = HOST.post(ENDPOINT, cxt)
```

- Also `tensor.size` and `tensor.dtype` are throwing `not found` in `tests/client/test_tensor.py`.

**Comment by haydnv** [comment]
Sorry, forgot to update the demo server! Just FYI, you can run a local host with the latest features by following the instructions in the contributor guide: https://github.com/haydnv/tinychain/blob/main/CONTRIBUTING.md

The issue with Tensor.split is fixed in commit 93e0fb0d and I've updated the demo server.
