### ISSUE TITLE
Division to integer problem

### ISSUE THREAD

**Issue by mukahraman** [haydnv/tinychain#65]
Dividing to integer is not allowed and I couldn't find any way to convert to float.
`tc.F32` and `tc.Float` fails to return `float` from integer input. My expectation is both should return float.

For convenience,
```
cxt = tc.Context()
cxt.x = tc.tensor.Dense.ones((3, 3))
cxt.y = cxt.x/tc.Float(3)
# cxt.y = cxt.x/tc.Float(cxt.x.shape[0])
actual = HOST.post(ENDPOINT, cxt)
print(actual)
```

**Comment by haydnv** [comment]
When you use a TinyChain state type like `F32`, the purpose is to inform the calling code of what type to expect (in order to access its API), not to force a cast to a specific type. For example, calling `tc.String(false).render(...)` will fail at runtime with a NotFound exception, because a Boolean has no such method as "render." The issue with your code is that `3` is an integer--you can use `3.` or `3.0` instead, or `tc.Int(3).cast(tc.F32)`, or you can cast the tensor `x` like `cxt.x.cast(tc.F32)`, but I recommend just passing the dtype you want as a parameter to the `ones` constructor like `tc.tensor.Dense.ones((3, 3), tc.F32)`. I added a test in commit 7e9e1a46 with some examples.
