### ISSUE TITLE
Network training time

### ISSUE THREAD

**Issue by KOHbDS** [haydnv/tinychain#78]
I've completed a network workout for dataset (5 objects)  and 100 learning epochs:
My NN
```python
Dense(4, 3. activation=Sigmoid)
Dense(3, 2. activation=ReLU)
Dense(2, 1. activation=Sigmoid)

loss_functions = MSE
optimizer = Adam
```
inputs had shape 5X4

This training took more than **60** minutes. Therefore, I propose to include in the documentation information about the correct installation of `TinyChain` with the parameter `--request_ttl=86400`

**Comment by haydnv** [comment]
It looks like most of the lag is coming from the `BlockListReduce.read_values` function, which slices the source tensor once per for every individual coordinate to read: https://github.com/haydnv/tinychain/blob/main/host/tensor/src/dense/access.rs#L1416

I added two tracking issues in the array library:
 * https://github.com/haydnv/afarray/issues/1
 * https://github.com/haydnv/afarray/issues/2

Once these are implemented I can update `BlockListReduce.read_values` to handle small `Tensor`s more efficiently. Re: the `request_ttl` startup flag, it is documented if you run `tinychain --help` but in this case I think the real solution is support for background tasks (issue #32).

**Comment by haydnv** [comment]
This should be slightly improved by #89 but there's still a lot more optimization to do

**Comment by haydnv** [comment]
I looked into this more and there are a few main contributing factors to slow training times:
 1. TinyChain has more CPU-bound overhead for small tensors (megabytes or less) than other ML platforms because it treats them like large tensors, and more overhead in general in order to support transactional versioning.
 2. TinyChain computes layer activation twice, once on the forward pass and once on the backward pass (this should be fixed soon), which can be up to a 50% increase in the time taken by each training cycle.
 3. TinyChain does not do garbage collection within a single transaction. It's designed with the assumption that each transaction is small and completes quickly. So, all the intermediate tensors (the results of every call to `.copy()`) fill up the cache and lead to disk I/O.
 4. In the extreme case of a convolutional neural net with lots of intermediary tensors, TinyChain can't flush the cache to disk fast enough and eventually crashes with an OOM error.

The main solution to these issues is to use a hosted training service which runs one training cycle per transaction. This is also necessary in order to distribute training across multiple servers.

**Comment by haydnv** [comment]
In the short term there should be a small speedup from 2c7b4e56 and 9cd7592, but as long as multiple training cycles are running in a single transaction they will become slower and slower with each iteration.

**Comment by haydnv** [comment]
This appears to now be resolved but please re-open this issue if you continue to experience abnormally slow model training times
